Update create_internal_pr_on_fork.yml

diff --git a/.github/workflows/create_internal_pr_on_fork.yml b/.github/workflows/create_internal_pr_on_fork.yml
--- a/.github/workflows/create_internal_pr_on_fork.yml
+++ b/.github/workflows/create_internal_pr_on_fork.yml
@@ -26,15 +26,6 @@ jobs:
         run: |
           git checkout -b fork-pr-${{ github.event.pull_request.number }} base/${{ github.base_ref }}
       
-      - name: Apply PR changes
-        run: |
-          git merge --no-commit --no-ff ${{ github.event.pull_request.head.sha }}
-      
-      - name: Check for changes
-        id: check_changes
-        run: |
-          git diff --exit-code --staged || echo "changes=true" >> $GITHUB_OUTPUT
-
       - name: Get original committer info
         id: get_committer_info
         run: |
@@ -42,19 +33,41 @@ jobs:
           COMMITTER_EMAIL=$(git log -1 --pretty=format:'%ae' ${{ github.event.pull_request.head.sha }})
           echo "committer_name=${COMMITTER_NAME}" >> $GITHUB_OUTPUT
           echo "committer_email=${COMMITTER_EMAIL}" >> $GITHUB_OUTPUT
+      
+      - name: Set git identity
+        run: |
+          git config user.name "${{ steps.get_committer_info.outputs.committer_name }}"
+          git config user.email "${{ steps.get_committer_info.outputs.committer_email }}"
+      
+      - name: Apply PR changes
+        run: |
+          if ! git merge --no-commit --no-ff --signoff ${{ github.event.pull_request.head.sha }}; then
+            echo "Merge failed. There might be conflicts."
+            git merge --abort
+            exit 1
+          fi
+      
+      - name: Check for changes
+        id: check_changes
+        run: |
+          git diff --exit-code --staged || echo "changes=true" >> $GITHUB_OUTPUT
 
       - name: Commit changes
         if: steps.check_changes.outputs.changes == 'true'
         run: |
-          git config user.name "${{ steps.get_committer_info.outputs.committer_name }}"
-          git config user.email "${{ steps.get_committer_info.outputs.committer_email }}"
-          git commit -m "Committing changes detected in PR #${{ github.event.pull_request.number }}"
+          COMMIT_MSG=$(git log -1 --pretty=%B ${{ github.event.pull_request.head.sha }})
+          git commit -m "$COMMIT_MSG" --signoff
+
+      - name: Push changes
+        if: steps.check_changes.outputs.changes == 'true'
+        run: |
+          git push origin fork-pr-${{ github.event.pull_request.number }}
 
       - name: Log branch information
         run: |
           echo "PR number: ${{ github.event.pull_request.number }}"
           echo "SHA: ${{ github.sha }}"
-          echo "Branch: fork-${{ github.event.pull_request.number }}"
+          echo "Branch: fork-pr-${{ github.event.pull_request.number }}"
           echo "Base ref: ${{ github.base_ref }}"
 
       - name: Create PR to main
@@ -64,7 +77,7 @@ jobs:
         with:
           token: ${{ secrets.GITHUB_TOKEN }}  
           commit-message: 'Creating a PR from fork PR #${{ github.event.pull_request.number }}'
-          branch: fork-${{ github.event.pull_request.number }}
+          branch: fork-pr-${{ github.event.pull_request.number }}
           base: ${{ github.base_ref }}
           title: 'NPC updates for fork PR #${{ github.event.pull_request.number }}'
           body: 'This PR contains NPC updates from the fork PR #${{ github.event.pull_request.number }}. Apply changes with `/apply` command.'
